spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 0

